- name: testing role terraform-logserver
  hosts: localhost
  gather_facts: false

  # variables passed from AWX job survey:

  # {{ aws_region_name }}
  # {{ aws_cidr_block_from_port_80 }}

  # {{ es_domain_name }}
  # {{ es_version }}
  # {{ es_instance_count }}
  # {{ es_instance_type }}
  # {{ es_volume_size }}

  # {{ ec2_name }}
  # {{ ec2_instance_type }}
  # {{ ec2_docker_compose }}
  # {{ ec2_nginx_version }}
  # {{ ec2_logstash_version }}

  vars:
    ec2_ssh_public_key: "{{ ssh_public_key }}"

  tasks:

    - name: set AWS region name
      set_fact:
        aws_region: "{{ (lookup('file', 'aws_region_names.json') | from_json).get( aws_region_name | regex_replace('[().]','') | regex_replace('[\ ]','_') ) }}"

    - include_role:
        name: terraform-logserver
