- name: testing role terraform-logserver
  hosts: localhost
  gather_facts: false

  # variables passed from AWX job survey:

  # {{ aws_region_name | string }}

  # {{ es_domain_name | string }}
  # {{ es_version | string }}
  # {{ es_instance_count | integer }}
  # {{ es_instance_type | string }}
  # {{ es_volume_size | integer }}

  # {{ aws_vpc_default | string }}
  # {{ aws_vpc_id | string }}
  # {{ aws_subnet_id | string }}
  # {{ aws_cidr_block_from_port_80 | string }}

  # {{ ec2_instance_type | string }}
  vars:

    ec2_docker_compose: 1.19.0
    ec2_nginx_version: 1.13
    ec2_logstash_version: 6.2.1

  tasks:

    - name: set AWS region name
      set_fact:
        aws_region: "{{ (lookup('file', 'aws_region_names.json') | from_json).get( aws_region_name | regex_replace('[().]','') | regex_replace('[\ ]','_') ) }}"

    - include_role:
        name: terraform-logserver
      vars:
        ec2_name: "logger-proxy-{{ es_domain_name }}"
        ec2_instance_type: "{{ ec2_instance_type }}"
        ec2_ssh_public_key: "{{ ssh_public_key }}"
        es_domain_name: "{{ es_domain_name }}"
        es_version: "{{ es_version }}"
        es_instance_count: "{{ es_instance_count }}"
        es_instance_type: "{{ es_instance_type }}"
        es_volume_size: "{{ es_volume_size }}"
        aws_vpc_id: "{{ aws_vpc_id }}"
        aws_subnet_id: "{{ aws_subnet_id }}"
        aws_vpc_default: "{{  aws_vpc_default }}"
        aws_cidr_block_from_port_80: "{{ aws_cidr_block_from_port_80 }}"

