- name: testing role terraform-logserver
  hosts: localhost
  gather_facts: false

  # variables passed from AWX job survey:

  # {{ aws_region_name }}
  # {{ aws_cidr_block_from_port_80 }}

  # {{ es_domain_name }}
  # {{ es_version }}
  # {{ es_instance_count }}
  # {{ es_instance_type }}
  # {{ es_volume_size }}

  vars:

    ec2_name: "logserver-proxy"
    ec2_instance_type: "t2.small"
    ec2_docker_compose: "1.19.0"
    ec2_nginx_version: "1.13"
    ec2_logstash_version: "6.2.1"
    ec2_ssh_public_key: "{{ ssh_public_key }}"

  tasks:

    - name: set AWS region name
        set_fact:
          aws_region: "{{ (lookup('file', 'aws_region_names.json') | from_json).get( aws_region_name | regex_replace('[().]','') | regex_replace('[\ ]','_') ) }}"
        tags: ['always']

    - include_role:
        name: terraform-logserver
      vars:
        aws_cidr_block_from_port_80: "{{ aws_cidr_block_from_port_80 }}"
