  - name: get Ambisafe VPC id
    local_action:
      module: ec2_vpc_net_facts
      region: "{{ aws_region }}"
      filters:
        isDefault: true
    register: ambisafe_vpc

  - name: set VPC id
    set_fact:
      ambisafe_vpc_id: "{{ ambisafe_vpc.vpcs.0.id }}"
    when: ambisafe_vpc.vpcs is defined

  - assert:
      that: "ambisafe_vpc_id is defined"
      msg: "AMBISAFE VPC [{{ aws_vpc_name }}] IS NOT FOUND IN AWS REGION [{{ aws_region }}]"

  - name: get VPC subnet ids
    local_action:
      module: ec2_vpc_subnet_facts
      region: "{{ aws_region }}"
      filters:
        vpc-id: "{{ ambisafe_vpc_id }}"
    register: ambisafe_vpc_sub

  - name: set VPC subnet id
    set_fact:
      ambisafe_vpc_subnet_id: "{{ ambisafe_vpc_sub.subnets.0.id }}"
    when: ambisafe_vpc_sub.subnets is defined

  - assert:
      that: "ambisafe_vpc_subnet_id is defined"
      msg: "SUBNETS FOR AMBISAFE VPC [{{ aws_vpc_name }}] ARE NOT FOUND IN AWS REGION [{{ aws_region }}]"